### ISSUE TITLE
CPU Utilization Avg % not displaying data

### ISSUE THREAD

**Issue by sawo1337** [jorgedlcruz/vmware-grafana#11]
Hi,
I've been trying to figure out why is there no data for usage_average in vsphere_vm_cpu - I can see in the telegraf.conf that there is no field usage_average? I've checked the official config here - https://github.com/influxdata/telegraf/tree/master/plugins/inputs/vsphere but the closest thing in vm_metric_include is cpu.used.summation - am I missing something?

It is interesting that in the sample output, they are showing vsphere_vm_cpu generating data for usage_average, but in the actual sample config, there is no such field? Is this supposed to be generated dynamically somehow, or calculated in the graph itself?

I'm collecting data from ESXi 6.7 hosts via vCenter Server Appliance 6.7

I know this is a most likely bug within Telegraf itself, just want to check if this is actually showing data for other people in the VM dashboard?

**Comment by sawo1337** [comment]
sorry, not sure why it didn't work the first time, just added it manually again to the telegraf conf and it started to collect data

**Comment by ericwu1121** [comment]
Hi @sawo1337 , I got the same issue in my grafana, did you manually add "cpu.utilization.average" in "vm_metric_include" block ?

**Comment by sawo1337** [comment]
> Hi @sawo1337 , I got the same issue in my grafana, did you manually add "cpu.utilization.average" in "vm_metric_include" block ?

I'm using cpu.usage.average in "vm_metric_include" - that works with VCSA 6.7 and the latest telegraf.

**Comment by ericwu1121** [comment]
> > Hi @sawo1337 , I got the same issue in my grafana, did you manually add "cpu.utilization.average" in "vm_metric_include" block ?
> 
> I'm using cpu.usage.average in "vm_metric_include" - that works with VCSA 6.7 and the latest telegraf.

Thanks it's works !!

**Comment by sergenaras** [comment]
Hi guys, 

I have the same issue. "cpu.usage.average" is work but "cpu.utilization.average" is not. What can I do for this situation?

**Comment by sawo1337** [comment]
"cpu.usage.average" and "cpu.utilization.average" provide the same data. What kind of data are you trying to get?

**Comment by sergenaras** [comment]
Really? I thought they were pointing to different points. Thank's for information.

**Comment by sawo1337** [comment]
It is all percentage usage so its the same thing, just named differently across measurements (VM,Host,etc)
